# Generated by Django 2.1.1 on 2018-12-26 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='database',
            fields=[
                ('Id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('botanical_name', models.CharField(blank=True, default='', max_length=255)),
                ('family', models.CharField(blank=True, default='', max_length=255)),
                ('english_name', models.CharField(blank=True, default='', max_length=255)),
                ('ayurvedic_name', models.CharField(blank=True, default='', max_length=255)),
                ('unani_name', models.CharField(blank=True, default='', max_length=255)),
                ('sidda_tamil_name', models.CharField(blank=True, default='', max_length=255)),
                ('folk_name', models.CharField(blank=True, default='', max_length=255)),
                ('habiatat', models.CharField(blank=True, default='', max_length=255)),
                ('disease', models.CharField(blank=True, default='', max_length=255)),
                ('part', models.CharField(blank=True, default='', max_length=255)),
                ('compound', models.CharField(blank=True, default='', max_length=255)),
                ('references', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
    ]
